name: "🐞 Bug report"
description: Reporte um problema encontrado no Backlog DIM
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar! Evite inserir dados pessoais reais.
  - type: input
    id: summary
    attributes:
      label: Resumo
      description: Descreva brevemente o bug
      placeholder: Ex. Erro 500 ao salvar processo
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Liste os passos
      placeholder: |
        1. Ir para /dashboard
        2. Clicar em "Novo Processo"
        3. Preencher campos ...
        4. Clicar em "Salvar"
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamento atual
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Área afetada
      options:
        - Frontend (Next.js/React/MUI)
        - API (App Router /api)
        - Banco/Prisma
        - Infra/CI
        - Documentação
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/erros
      description: Cole trechos relevantes (sem dados sensíveis)
      render: bash
  - type: input
    id: version
    attributes:
      label: Versão/commit
      placeholder: Ex. 0.2.90 / abcdef1
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: Não inclui dados pessoais reais
          required: true
        - label: Verifiquei se ocorre em `develop` mais recente
          required: true
