blank_issues_enabled: false
contact_links:
  - name: Segurança – Política de Reporte
    url: https://github.com/anpdgovbr/backlog-dim/blob/main/SECURITY.md
    about: Leia antes de reportar vulnerabilidades
  - name: Suporte – Backlog DIM
    url: https://github.com/anpdgovbr/backlog-dim/blob/main/SUPPORT.md
    about: Como obter suporte
