blank_issues_enabled: false
contact_links:
  - name: Segurança – Política de Reporte
    url: ../SECURITY.md
    about: Leia antes de reportar vulnerabilidades
  - name: Suporte – Backlog DIM
    url: ../SUPPORT.md
    about: Como obter suporte
