name: "📝 Documentação"
description: Solicitar ajustes ou adicionar documentação
labels: ["type: docs"]
body:
  - type: input
    id: summary
    attributes:
      label: Resumo
      placeholder: Ex. Atualizar seção de instalação no README
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Detalhes
      description: O que precisa ser alterado/criado?
  - type: dropdown
    id: area
    attributes:
      label: Área
      options:
        - README
        - /docs
        - Comentários JSDoc/TS
        - Guia de contribuição
