name: "❓ Dúvida"
description: Abra uma pergunta técnica geral
labels: ["type: question"]
body:
  - type: input
    id: topic
    attributes:
      label: Tópico
      placeholder: Ex. NextAuth callback / Prisma relation
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Pergunta
      description: Descreva a dúvida objetivamente
      placeholder: |
        Qual o padrão de HOC para páginas de visão?
